# The name of your pipeline, which will appear in GitHub Actions
name: Java Maven Tests CI

# When the pipeline should run
on:
  push:
    # Run on commits to the main branch
    branches: [ master, main ]
  pull_request:
    # Run on creation of a Pull Request targeting the main branch
    branches: [ master, main ]

# Define the jobs
jobs:
  build:
    name: Run ${{ matrix.test-group }} tests
    # Run on the standard Ubuntu virtual machine
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Continue the tests running in case if one of them is failed
      matrix:
        test-group: ["smoke", "regression"]

    # Steps for execution
    steps:
      - name: Checkout Repository
        # Action to check out the repository code
        uses: actions/checkout@v4

      - name: Set up Java 17
        # Action to set up the Java environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Enable Maven caching for faster dependency downloads
          cache: maven

      #- name: Run Maven Tests
        # Execute the tests using the Maven 'test' goal
        # Pass the selenide.headless property to ensure tests run without a GUI
        #run: mvn test -Dselenide.headless=true
      - name: Run Tests by Group
        run: mvn test -Dgroups="${{ matrix.test-group }}" -Dselenide.headless=true # Using parameter Dgroups for filter by tags

      - name: Final Status Check (Success)
        # This step only runs if the previous 'mvn test' step was successful
        if: success()
        #run: echo "Tests passed successfully! Continuous Integration is good."
        run: echo "Group ${{ matrix.test-group }} completed successfully!"

      - name: Report Failure
        # This step only runs if the tests failed
        if: failure()
        #run: echo "Tests failed! Check the test results in the workflow logs."
        run: echo "Tests failed in group ${{ matrix.test-group }}

        #Save screenshot if case of fail
      - name: Upload Selenide reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.test-group }}
          path: build/reports/tests/
          retention-days: 5
